### ISSUE TITLE
Multiple classes

### ISSUE THREAD

**Issue by vbauer** [pushtorefresh/java-private-constructor-checker#12]
It will be very useful to have possibility to check multiple classes simultaneously (something like `forClasses`). Now, it's necessary to duplicate code for each class.

**Comment by artem-zinnatullin** [comment]
Looks like a good idea! I'll work on it.

**Comment by artem-zinnatullin** [comment]
@vbauer v1.1.0 with this feature was just published to Maven Central and it should be available in 10-20 minutes :)

**Comment by vbauer** [comment]
Great, thank you!
