### ISSUE TITLE
Private Constructor with parameter

### ISSUE THREAD

**Issue by vanniktech** [pushtorefresh/java-private-constructor-checker#16]
I want to test a class that it has only exactly one constructor which is private and takes one argument. 

I thought

``` java
PrivateConstructorChecker.forClass(MyClass.class).check();
```

would do it but it gave me an exception back:

> java.lang.AssertionError: class onactivityresult.compiler.Parameter has non-default constructor with some parameters

So I guess this was a design decision. Would you be open for a new API to test the described behavior?

Maybe something alone the lines of

``` java
PrivateConstructorChecker.forClass(MyClass.class).expectWithParameters(...).check();
```

Obviously `expectWithParameters` would return a different builder so you're not able to call `expectedExceptionMessage` and `expectedTypeOfException` on it.

For the case of multiple constructors we could do `expectMultipleWithParameters(`.

**Comment by artem-zinnatullin** [comment]
Hi @vanniktech! 

It was a design decision, yes. Basically when you have private constructors with arguments that means that you then provide some static methods or other solutions to instantiate objects. While we wanted to check that class is not instantiable but looks like we chose very generic name for the library :smile: 

So..  if you really want to use private-constructor-checker for such purposes, well, why not I guess :smile_cat: 

@nikitin-da what do you think about this?

**Comment by artem-zinnatullin** [comment]
@vanniktech if @nikitin-da won't be against it — feel free to PR this! I'll be able to release new versions  on Thursday.

**Comment by nikitin-da** [comment]
Hi, guys! `not-instantiable-class-checker` it might be fun name =)
I'm not against to make it more generic. It will be easier to write test for class separately of it's builder's or etc.
BTW, @artem-zinnatullin  Happy birthday, Man!! :birthday: :fireworks:

**Comment by artem-zinnatullin** [comment]
Thanks bro :)

On Wed, Dec 16, 2015, 09:43 Dmitrii Nikitin notifications@github.com
wrote:

> Hi, guys! not-instantiable-class-checker it might be fun name =)
> I'm not against to make it more generic. It will be easier to write test
> for class separately of it's builder's or etc.
> BTW, @artem-zinnatullin https://github.com/artem-zinnatullin Happy
> birthday, Man!! [image: :birthday:] [image: :fireworks:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pushtorefresh/java-private-constructor-checker/issues/16#issuecomment-165015470
> .
> 
> ## 

@artem_zin

**Comment by vanniktech** [comment]
Happy birthday @artem-zinnatullin :cake: :beer: 

@nikitin-da are you suggesting a new class for that or do you wanna use the same one `PrivateConstructorChecker`?

**Comment by artem-zinnatullin** [comment]
@vanniktech thanks!

I think it could live right in `PrivateConstructorChecker` since you want to check private constructor :smiley:

**Comment by nikitin-da** [comment]
@vanniktech Yep! I think use the same class will be right.

**Comment by vanniktech** [comment]
Okay I'll work on something.

**Comment by nikitin-da** [comment]
@vanniktech thank you

**Comment by vanniktech** [comment]
Would you guys be so kind and review #17 first?
